name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          cd client
          npm install --legacy-peer-deps
          npm install -g firebase-tools

      - name: Build project
        run: npm run build
        working-directory: client

      - name: Verify Firebase files
        run: |
          ls -la client/firebase.json
          ls -la client/.firebaserc
          cat client/firebase.json

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: client/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Verify deployment files
        run: |
          ls -la client/
          ls -la client/firebase.json
          ls -la client/.firebaserc
          cat client/firebase.json

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
          working-directory: client
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}} 
